/**
 * ============================================================
 * 04_AuditService.gs
 * RENTAL OPERATIONS MVP
 * ============================================================
 *
 * Central audit logging service.
 *
 * Responsibilities:
 *
 * - Record CREATE operations
 * - Record UPDATE operations
 * - Record STATUS_CHANGE operations
 * - Record SYSTEM operations
 * - Serialize before/after values safely
 *
 * Audit destination:
 *
 * 30_AuditLog
 *
 * Expected columns:
 *
 * audit_id
 * timestamp
 * actor_type
 * actor_id
 * action
 * entity_type
 * entity_id
 * old_value
 * new_value
 *
 * IMPORTANT:
 *
 * - Audit IDs are generated by IdService.
 * - Timestamps use CONFIG.TIMEZONE.
 * - AuditService should not contain business validation.
 * - AuditService should not modify the business entity.
 *
 * ============================================================
 */

const AuditService = (() => {
  /**
   * ==========================================================
   * INTERNAL HELPERS
   * ==========================================================
   */

  /**
   * ----------------------------------------------------------
   * TIMESTAMP
   * ----------------------------------------------------------
   */

  function timestamp() {
    return Utilities.formatDate(
      new Date(),
      CONFIG.TIMEZONE,
      CONFIG.DATE_FORMATS.DATETIME,
    );
  }

  /**
   * ----------------------------------------------------------
   * SERIALIZE VALUE
   * ----------------------------------------------------------
   *
   * Converts values into safe strings for storage in the
   * audit sheet.
   *
   * Examples:
   *
   * object:
   *   {"status":"ACTIVE"}
   *
   * string:
   *   ACTIVE
   *
   * null:
   *   ""
   */

  function serialize(value) {
    if (value === undefined || value === null) {
      return "";
    }

    if (value instanceof Date) {
      return Utilities.formatDate(
        value,
        CONFIG.TIMEZONE,
        CONFIG.DATE_FORMATS.DATETIME,
      );
    }

    if (typeof value === "object") {
      try {
        return JSON.stringify(value);
      } catch (error) {
        return String(value);
      }
    }

    return String(value);
  }

  /**
   * ----------------------------------------------------------
   * NORMALIZE ACTOR ID
   * ----------------------------------------------------------
   */

  function normalizeActorId(actorId) {
    if (
      actorId === undefined ||
      actorId === null ||
      String(actorId).trim() === ""
    ) {
      return CONFIG.DEFAULTS.ACTOR_ID;
    }

    return String(actorId).trim();
  }

  /**
   * ----------------------------------------------------------
   * NORMALIZE ACTOR TYPE
   * ----------------------------------------------------------
   */

  function normalizeActorType(actorType) {
    if (
      actorType === undefined ||
      actorType === null ||
      String(actorType).trim() === ""
    ) {
      return CONFIG.DEFAULTS.ACTOR_TYPE;
    }

    return String(actorType).trim().toUpperCase();
  }

  /**
   * ----------------------------------------------------------
   * NORMALIZE ACTION
   * ----------------------------------------------------------
   */

  function normalizeAction(action) {
    if (
      action === undefined ||
      action === null ||
      String(action).trim() === ""
    ) {
      throw new Error("Audit action is required.");
    }

    return String(action).trim().toUpperCase();
  }

  /**
   * ----------------------------------------------------------
   * NORMALIZE ENTITY TYPE
   * ----------------------------------------------------------
   */

  function normalizeEntityType(entityType) {
    if (
      entityType === undefined ||
      entityType === null ||
      String(entityType).trim() === ""
    ) {
      throw new Error("Audit entity type is required.");
    }

    return String(entityType).trim().toUpperCase();
  }

  /**
   * ----------------------------------------------------------
   * NORMALIZE ENTITY ID
   * ----------------------------------------------------------
   */

  function normalizeEntityId(entityId) {
    if (entityId === undefined || entityId === null) {
      return "";
    }

    return String(entityId).trim();
  }

  /**
   * ==========================================================
   * CORE AUDIT FUNCTION
   * ==========================================================
   */

  /**
   * ----------------------------------------------------------
   * LOG
   * ----------------------------------------------------------
   *
   * Generic audit method.
   *
   * Parameters:
   *
   * action
   * entityType
   * entityId
   * oldValue
   * newValue
   * actorId
   * actorType
   */

  function log(
    action,
    entityType,
    entityId,
    oldValue,
    newValue,
    actorId,
    actorType,
  ) {
    const normalizedAction = normalizeAction(action);

    const normalizedEntityType = normalizeEntityType(entityType);

    const normalizedEntityId = normalizeEntityId(entityId);

    const normalizedActorId = normalizeActorId(actorId);

    const normalizedActorType = normalizeActorType(actorType);

    const auditRecord = {
      audit_id: IdService.nextId("AUDIT"),

      timestamp: timestamp(),

      actor_type: normalizedActorType,

      actor_id: normalizedActorId,

      action: normalizedAction,

      entity_type: normalizedEntityType,

      entity_id: normalizedEntityId,

      old_value: serialize(oldValue),

      new_value: serialize(newValue),
    };

    return BaseRepository.insert(CONFIG.SHEETS.AUDIT_LOG, auditRecord);
  }

  /**
   * ==========================================================
   * CREATE AUDIT
   * ==========================================================
   */

  /**
   * ----------------------------------------------------------
   * LOG CREATE
   * ----------------------------------------------------------
   *
   * Example:
   *
   * AuditService.logCreate(
   *   'UNIT',
   *   unit.unit_id,
   *   unit,
   *   actorId
   * );
   */

  function logCreate(entityType, entityId, newValue, actorId, actorType) {
    return log(
      "CREATE",
      entityType,
      entityId,
      null,
      newValue,
      actorId,
      actorType,
    );
  }

  /**
   * ==========================================================
   * UPDATE AUDIT
   * ==========================================================
   */

  /**
   * ----------------------------------------------------------
   * LOG UPDATE
   * ----------------------------------------------------------
   *
   * Stores both the previous and resulting state.
   */

  function logUpdate(
    entityType,
    entityId,
    oldValue,
    newValue,
    actorId,
    actorType,
  ) {
    return log(
      "UPDATE",
      entityType,
      entityId,
      oldValue,
      newValue,
      actorId,
      actorType,
    );
  }

  /**
   * ==========================================================
   * STATUS CHANGE AUDIT
   * ==========================================================
   */

  /**
   * ----------------------------------------------------------
   * LOG STATUS CHANGE
   * ----------------------------------------------------------
   *
   * oldStatus and newStatus may be strings or objects.
   *
   * Example:
   *
   * AuditService.logStatusChange(
   *   'UNIT',
   *   'UNIT-000001',
   *   'ACTIVE',
   *   'INACTIVE',
   *   actorId
   * );
   */

  function logStatusChange(
    entityType,
    entityId,
    oldStatus,
    newStatus,
    actorId,
    actorType,
  ) {
    return log(
      "STATUS_CHANGE",
      entityType,
      entityId,
      oldStatus,
      newStatus,
      actorId,
      actorType,
    );
  }

  /**
   * ==========================================================
   * SYSTEM AUDIT
   * ==========================================================
   */

  /**
   * ----------------------------------------------------------
   * LOG SYSTEM
   * ----------------------------------------------------------
   *
   * Maintains compatibility with the existing Phase 1 API:
   *
   * logSystem(
   *   action,
   *   entityType,
   *   entityId,
   *   oldValue,
   *   newValue
   * )
   *
   * Optional actorId / actorType parameters are also accepted.
   */

  function logSystem(
    action,
    entityType,
    entityId,
    oldValue,
    newValue,
    actorId,
    actorType,
  ) {
    return log(
      action,
      entityType,
      entityId,
      oldValue,
      newValue,
      actorId || CONFIG.DEFAULTS.ACTOR_ID,
      actorType || CONFIG.DEFAULTS.ACTOR_TYPE,
    );
  }

  /**
   * ==========================================================
   * QUERY HELPERS
   * ==========================================================
   */

  /**
   * ----------------------------------------------------------
   * GET AUDIT BY ID
   * ----------------------------------------------------------
   */

  function getAuditById(auditId) {
    if (
      auditId === undefined ||
      auditId === null ||
      String(auditId).trim() === ""
    ) {
      throw new Error("auditId is required.");
    }

    return BaseRepository.findById(
      CONFIG.SHEETS.AUDIT_LOG,
      "audit_id",
      String(auditId).trim(),
    );
  }

  /**
   * ----------------------------------------------------------
   * GET AUDIT FOR ENTITY
   * ----------------------------------------------------------
   */

  function getAuditForEntity(entityType, entityId) {
    const normalizedEntityType = normalizeEntityType(entityType);

    const normalizedEntityId = normalizeEntityId(entityId);

    return BaseRepository.findByField(
      CONFIG.SHEETS.AUDIT_LOG,
      "entity_id",
      normalizedEntityId,
    ).filter(
      (record) =>
        String(record.entity_type).trim().toUpperCase() ===
        normalizedEntityType,
    );
  }

  /**
   * ----------------------------------------------------------
   * GET ALL AUDIT RECORDS
   * ----------------------------------------------------------
   */

  function getAll() {
    return BaseRepository.findAll(CONFIG.SHEETS.AUDIT_LOG);
  }

  /**
   * ==========================================================
   * PUBLIC API
   * ==========================================================
   */

  return {
    timestamp,

    serialize,

    log,

    logCreate,

    logUpdate,

    logStatusChange,

    logSystem,

    getAuditById,

    getAuditForEntity,

    getAll,
  };
})();
